### ISSUE TITLE
pause menu didn't appear

### ISSUE THREAD

**Issue by JustDefend** [tewtal/itemrandomizerweb#17]
within draygon's room, I attempted to gravity jump while I had blue suit. however, when I paused the game - the screen would black out and no pause menu appeared. the energy, ammo and map hud were still displayed.

**Comment by tewtal** [comment]
This seems pretty strange and I'm not sure what could cause this. 
Do you have maybe some video capture of this happening and do you still have the .sfc-file that this happened in?
That would help me debugging this a bit and figure out what's wrong.

**Comment by JustDefend** [comment]
https://clips.twitch.tv/DreamyGoldenYakOMGScoots

**Comment by JustDefend** [comment]
[Item_Randomizer_TX8655177.zip](https://github.com/tewtal/itemrandomizerweb/files/1257705/Item_Randomizer_TX8655177.zip)

**Comment by awilkester** [comment]
just fixed this with recent changes
