### ISSUE TITLE
No items if starting from existing file

### ISSUE THREAD

**Issue by InsaneFirebat** [tewtal/itemrandomizerweb#2]
Items will not be spawned if starting from a save created by the intro demo. 

1. From a freshly randomized ROM, fast foward until the first intro demo plays
2. Interrupt the demo after seeing the ship
3. Continue through the menu to file selection (notice File A is now populated)
4. Start File A and progress to the Morph Ball location
5. Notice that there are no items in Classic Brinstar

**Comment by tewtal** [comment]
Thanks for the report.
I've been wondering what caused the random 00:00 files that people have reported, so it's nice to finally have a good way to reproduce that.

This should be easy to fix now that I know exactly what's going on :)
