### ISSUE TITLE
Useable with emulators?

### ISSUE THREAD

**Issue by allibear17** [tewtal/itemrandomizerweb#20]
I've been using Higan v104 but when loading a randomized rom, I get the Nintendo logo which is followed by nothing.  I've tried waiting a minute, fast forwarding and resenting.  Is this due to the rom itself I used in uploading, or the emulator?  If its the emulator, is there a suggested one I should try?  Thanks!

**Comment by InsaneFirebat** [comment]
Are you using an unheadered Super Metroid ROM? You can check the file size of the ROM to see if it's headered (3,073kb) or unheadered (3,072kb). You'll need to use an unheadered ROM for the randomizer to be applied correctly.

**Comment by allibear17** [comment]
Thank you
