### ISSUE TITLE
Compatibility with msu-1 patch

### ISSUE THREAD

**Issue by theonlydude** [tewtal/itemrandomizerweb#24]
Hello,

I'm using DarkShock Super Metroid MSU-1 patch on my SD2SNES and it's incompatible with the patch max_ammo_display.ips (I have a black screen after starting a new game).

Source of the DarkShock patch: https://github.com/mlarouche/SuperMetroid-MSU1
IPS patch: https://www.romhacking.net/hacks/2393/

Could you add an option on itemrandomizerweb to not incude the max_ammo_display.ips patch ?

Regards,
Manu

**Comment by theonlydude** [comment]
Hello,

I've found a workaround using ipsanti to remove the max_ammo_display.ips patch after randomizing the rom and before applying the msu-1 patch (http://bin.smwcentral.net/u/7298/ipsanti.exe).

Regards,
Manu.

**Comment by tewtal** [comment]
Nice that you found a workaround for now.
An interface for specifying what patches you want to include is something that is planned and will be coming in a future version.
