### ISSUE TITLE
Non-Pooled Randomization

### ISSUE THREAD

**Issue by IceMaverick** [tewtal/itemrandomizerweb#28]
Currently the randomizer makes note in the changes that items are randomized into two pools: major items/health and ammo. 
Are there any plans for randomization options to be non-pooled like this? One thing I enjoyed more about the Dessyreqt randomizer was that it was actually truly completely random. You had to check as much as possible because a major progression item might be sitting in a missile pack location or something. Would love to see some setting that allows items to be placed more freely in locations instead of only really caring about major item locations.

**Comment by tewtal** [comment]
An experimental mode that uses full randomization along with the "Tournament" difficulty has been implemented in the lastest code. It's not been pushed to the live website yet but will be in the near future.
