### ISSUE TITLE
Samus can get stuck in crouch with Screw Attack and no Morph Ball

### ISSUE THREAD

**Issue by serberoth** [tewtal/itemrandomizerweb#3]
In instances where you get Screw Attack before getting Morph Ball, you can get stuck when breaking blocks in certain rooms, such as the Landing Site (to the right of the ship) as well as the block to the Gauntlet, in Brinstar the Dachora Room.  This happens when the Samus breaks out of her spin and she gets stuck in a crouching position, since the player does not have the Morph Ball the player is stuck in this position and cannot get out.

I have been informed there is a combination of buttons that work going from the left that will get the player out of this position, but not from the right (or possibly vice-versa).  Either way this seems insufficient if the goal is to make this more accessible for players who want to join in and run SM item randomizer.  I would hate to see the solution to this be fixing the position of Morph Ball; however.  Fixing this key combination from both the left and right, seems both a win from the diversity perspective as well as the accessibility perspective; however, the combination should not be obscure and/or should be well publicized.

**Comment by tewtal** [comment]
This is something we've talked about and want to fix but we're not sure yet in what way. What you suggested is probably the first thing we'll see if it's possible to do because the inputs required to get out are pretty simple and is something we can publish in a mini-guide.

**Comment by tewtal** [comment]
This is not an issue anymore with the changes to the logic that gives you morph ball early. I'll close this for now and reopen it if we change the logic back to some point where this will be a needed fix again.
