### ISSUE TITLE
Open mode OX6357881 sticking point

### ISSUE THREAD

**Issue by shaneriley** [tewtal/itemrandomizerweb#33]
Brinstar green area, from main entrance, first red door to left locks you in the room until you clear it of enemies. Neither morph ball nor morph ball bombs have been collectible yet, so the game is inescapable.

**Comment by InsaneFirebat** [comment]
This softlock has been brought up a few times in the past. That room only leads to a map station, so there shouldn't be any reason to explore there. You'll need to be careful and have a good understanding of the world for open randomizers.
