### ISSUE TITLE
Generated Seeds not working on 1.8.0 updated sd2snes

### ISSUE THREAD

**Issue by lorvanos95** [tewtal/itemrandomizerweb#46]
Game partial loads to cut-scene but never finishes.

**Comment by InsaneFirebat** [comment]
Did you use a non-headered ROM when generating the seed? If the ROM has a header, all of the randomizer changes will be applied in the wrong places. Check the file size of your Super Metroid ROM. A non-headered ROM will be 3072KB, while one with a header would be 3073KB.

I believe programs for patching ROMs like LunarIPS have a feature to add/remove headers.
