### ISSUE TITLE
FX6330064 impossible to beat because of three suit upgrades locking each other out.

### ISSUE THREAD

**Issue by kewlan90** [tewtal/itemrandomizerweb#49]
On this Full Randomization seed, FX6330064, I believe it's impossible to complete because of the location of Speed Booster, Space Jump and Ice Beam. Neither of them can be acquired because they all require each other as following:

- Speed Booster is in the yellow door room above Samus's ship. To get this I needed either the Speed Booster itself or Space Jump.
- Space Jump is where it normally is, past Draygon's boss room, but to get there I needed either the Speed Booster, or the Ice Beam to do the "freeze Metroid and use as a platform" glitch.
- Ice Beam is also in Maridia, in the large room where the pipe goes through. It's in the spot where you have to use the Speed Booster and dash straight up.

I used a moon jump cheat to get to the Speed Booster and got the other items after that.

**Comment by moriwizz** [comment]
It's pretty simple to infinite bomb jump up to the room above Samus's ship. It's a trick you're going to want to know how to do if you're going to play randomizers. Infinite bomb jumping is an intended mechanic. The game plays a demo demonstrating the trick on the title screen.

**Comment by kewlan90** [comment]
Oh, it was that simple, huh? Thanks for the info and fast response!
