### ISSUE TITLE
HX7028680 - Garbled screens with Speed Booster

### ISSUE THREAD

**Issue by KyleBaran** [tewtal/itemrandomizerweb#50]
I played a few hard seeds before I noticed this problem. It likes to give the Speed Booster as a starting item, needing you to break the bomb wall into west Crateria, to get the Morph Ball. This is fine.

However, for some reason, on seed HX7028680, when I start to run fast, the screen gets garbled. This appears to be a visual glitch only. Not sure where it's messing up or why.

https://i.imgur.com/VvTPrSC.png

**Comment by moriwizz** [comment]
I don't get this glitch. However, this seed looks impossible.

**Comment by InsaneFirebat** [comment]
I believe this is possible in the vanilla game if you run through the door to terminator before the screen has a chance to scroll to the left. Sounds like that's what happened here, unless you can reproduce it some other way.

**Comment by KyleBaran** [comment]
Closing issue as @InsaneFirebat has indicated this potentially appears in the vanilla game and isn't specific to the randomizer (as far as I know)
