### ISSUE TITLE
Possible unbeatable seed 5608258 (version 2.3, normal difficulty)

### ISSUE THREAD

**Issue by DorkmasterFlek** [tewtal/itemrandomizerweb#6]
Entirely possible (read: likely) I'm overlooking something here, but I think I hit a wall with this seed...

Major items missing (I have everything else):
- Charge beam
- Wave beam
- Varia suit
- Speed booster
- Spring ball

I believe I've hit every possible major item location I can get to having everything else, including making some hell runs into upper Norfair to hit Bubble Mountain reserve tank, speed booster, and wave beam spots.  Obvious next major item locations I can think of that I can't get to:
- Reserve tank in Wrecked Ship (need speed booster; hit right side super spot, e-tank spot, and gravity suit already)
- Botwoon/Draygon (can't progress to Botwoon without speed booster; possible ice clip in mocktroid room IIRC but is this required on normal???)
- Crocomire + grapple beam area (can't get through the gate without wave beam; can't come in the back way without speed booster; also missing varia suit so more hell runs required???)
- Brinstar big pink sidehopper e-tank (need wave beam)
- E-tank below charge beam (need speed booster)

Normally I'd assume the issue is me, but since this is in beta and the latest versions had a bunch of behind the scenes changes according to the patch notes, I thought I'd let you guys take a look just in case.  I'm pretty sure I'm stuck barring some crazy tricks that it seems like shouldn't be required on normal difficulty...

**Comment by DorkmasterFlek** [comment]
UPDATE: I managed to get into spring ball room by getting up the intended route without space jump, but it was a reserve tank.  Learned the mocktroid ice clip to get into Botwoon and then Draygon, but Bowtoon e-tank, space jump, and plasma beam spots were all e-tanks.  Major areas left are Crocomire/grapple beam + lower Norfair, but I can't get in there unless I gate glitch and still no Varia.

**Comment by DorkmasterFlek** [comment]
UPDATE #2: Finally figured out the logic chain...  I had to gate glitch through the blue gate (with no Varia suit) in order to get to Crocomire.  Croco e-tank was wave beam (grapple was reserve tank), which lead back to Big Pink sidehopper room e-tank which was speed booster.  This then led to e-tank below charge beam, which was finally Varia.  So this seed required a gate glitch in the middle of a hell run, which seems pretty harsh for standard difficulty...

**Comment by InsaneFirebat** [comment]
@DorkmasterFlek The gate glitch to get to Crocomire is not too difficult. You can use regular missiles to do it, and recharge your energy on the respawning bugs nearby. Here are a couple videos from Crocomire RTA that demonstrate it.

https://youtu.be/Ebg_TaoS5Tk?t=8m15s
https://youtu.be/-zSeZd2V5oA?t=8m45s

**Comment by InsaneFirebat** [comment]
Guess I was a bit late. Glad you got through it!

**Comment by DorkmasterFlek** [comment]
Me too, thanks!  I just had no idea that would be a required thing to do on standard difficulty.  I'll have to practice that particular gate glitch given this information now.
