### ISSUE TITLE
Permission to use the source code in another application.

### ISSUE THREAD

**Issue by marcelodmc3** [tewtal/itemrandomizerweb#60]
Hello!

I'm currently fiddling around with the code and I have started to build an application for windows that works offline (C#/WinForms).

I'm using a slight modified version of the ItemRandomizer.fsproj project that is included in your solution.

As I could not find any lincense information on the project page, I want to ask if it's OK for me to download and use the code of the randomizer as the base for my solution.

My desktop version will be open source and the code hosted here on GitHub.

Thanks for your attention!

**Comment by tewtal** [comment]
Sorry for the really late answer, but yeah it's perfectly OK to use this code in your project.
