### ISSUE TITLE
502 Bad Gateway

### ISSUE THREAD

**Issue by ldc16** [tewtal/itemrandomizerweb#61]
I am also experiencing the Bad Gateway issue. My ROM file is unheadered and I was able to patch another hack with it so I don't think the problem is with the file. I also cannot use the .exe file since I'm on MacOS and do not have access to a Virtual Machine. Would you be able to provide a MacOS version of the Randomizer at some point? If not, having the web interface is fine as long as the downloads work.

**Comment by tewtal** [comment]
This should be fixed now.

**Comment by ldc16** [comment]
Awesome, now let's see if I get a nope tank as the first item in my inaugural run : )
