### ISSUE TITLE
Issue related to Super Missiles

### ISSUE THREAD

**Issue by enderbrah12** [tewtal/itemrandomizerweb#66]
So...my tracker (based on your randomizer) has a limit of 100 Super Missiles. But...I managed to find more than even 100 in my run. This is the screen with me having 105. Is the tracker the one with the error? Or is it the randomizer itself?

![image](https://user-images.githubusercontent.com/66192571/83344210-97fc9980-a2d1-11ea-9710-7d69160083ce.png) <-- What the tracker looks like. The green number means it's at it's max and can't go any higher.
![image](https://user-images.githubusercontent.com/66192571/83344214-a34fc500-a2d1-11ea-8b72-50b750918b38.png) <-- What the game looks like.

Thanks for the help in advance,

enderbrah12

P.S. The seed I'm using is CX8125325 on Casual Difficulty.

**Comment by InsaneFirebat** [comment]
The game can support up to around 32k of each ammo type, but the display in the HUD is only built to show 99 or less for Power Bombs and Super Missiles.. When it tries to bring the first digit over 9, it doesn't know what graphic to use and just picks the next bit of data in the list, which isn't a number at all.

I would guess that your tracker has that value erroneously capped at 100.

**Comment by enderbrah12** [comment]
Thanks for this information! I wasn't aware of this. I'll be sure to keep it in mind in the future!
