### ISSUE TITLE
Display seed number in-game

### ISSUE THREAD

**Issue by DorkmasterFlek** [tewtal/itemrandomizerweb#9]
It would be really nice if we could insert the seed number somewhere on the title screen or file select menu, maybe at the top of file select where it says "SAMUS DATA"?  Not sure how difficult this is, but it would make it easier to confirm racers are on the correct seed for the tournament.

**Comment by tewtal** [comment]
This is something I want to add, but it's somewhat of a low priority right now since it's pretty complex to do and there are more important things to work on right now. It will be added at some point though.

**Comment by tewtal** [comment]
This will be added in the next update as a combination of 4 random enemy names, replacing the "OPTION MODE" text in the top after you have selected a file. It'll look like this: [http://i.imgur.com/Jfjkjy6.png]
